/*  Cycle Text From .TXT (frames linked to slider)
    - Select a comp (and a text layer if you already have one), then run.
    - You’ll be prompted to choose a .txt file with one entry per line.
    - Script creates/ensures a "Frames Per Text" slider and wires the expression.
*/

(function () {
    app.beginUndoGroup("Cycle Text From TXT");

    var comp = app.project.activeItem;
    if (!(comp instanceof CompItem)) {
        alert("Select a composition first.");
        app.endUndoGroup();
        return;
    }

    // Target text layer: use selected TextLayer or create a new one
    var textLayer;
    if (comp.selectedLayers.length && comp.selectedLayers[0] instanceof TextLayer) {
        textLayer = comp.selectedLayers[0];
    } else {
        textLayer = comp.layers.addText("…");
    }

    // Pick a .txt file: one line per entry
    var file = File.openDialog("Select a .txt file (one line per entry)", "*.txt");
    if (!file) {
        app.endUndoGroup();
        return;
    }

    // Read file content safely
    try {
        // Prefer UTF-8; AE will still read ANSI if needed
        file.encoding = "UTF-8";
        if (!file.open("r")) throw new Error("Could not open file.");

        var content = file.read();
        file.close();

        // Normalize line endings to \n
        content = content.replace(/\r\n|\r|\n/g, "\n");        // normalize

        // Build a JS array literal of rows so the generated expression doesn't contain literal "\\n" escapes
        var rows = content.split("\n");
        var entryList = [];
        var parsedStrings = [];  // For preview
        for (var ri = 0; ri < rows.length; ri++) {
            var r = rows[ri];
            // Trim for preview
            var trimmed = r;
            while (trimmed.length && (trimmed.charCodeAt(0) <= 32)) trimmed = trimmed.substring(1);
            while (trimmed.length && (trimmed.charCodeAt(trimmed.length-1) <= 32)) trimmed = trimmed.substring(0, trimmed.length-1);
            if (trimmed.length) parsedStrings.push(trimmed);
            
            r = r.replace(/\\/g, "\\\\").replace(/\"/g, '\\\"').replace(/"/g, '\\"');
            entryList.push('"' + r + '"');
        }
        var entriesArrayLiteral = entryList.join(",");

        // Show preview dialog
        var previewMsg = "Preview (first 5 entries):\n\n";
        for (var pi = 0; pi < Math.min(5, parsedStrings.length); pi++) {
            previewMsg += (pi + 1) + ". " + parsedStrings[pi] + "\n";
        }
        if (parsedStrings.length > 5) {
            previewMsg += "\n... and " + (parsedStrings.length - 5) + " more";
        }
        if (!confirm(previewMsg + "\n\nProceed with applying expressions?")) {
            app.endUndoGroup();
            return;
        }

        // Create a comp-level null object with the Frames Per Text slider
        var nullLayer = comp.layers.addNull();
        nullLayer.name = "Cycling Text Control";
        var fx = nullLayer.property("ADBE Effect Parade");
        var slider = fx.addProperty("ADBE Slider Control");
        slider.name = "Frames Per Text";
        slider.property("ADBE Slider Control-0001").setValue(10); // default

        // Build expression
        // - Splits on \n that we injected above
        // - Optional trim & blank-line skip (kept simple for performance)
        // - Loops forever
    var NL = String.fromCharCode(10);
    var linesArr = [];
    linesArr.push("// Auto-generated by script: reads lines from your selected .txt (embedded at setup)");
    linesArr.push("var lines = [" + entriesArrayLiteral + "]; ");
    linesArr.push("// (Optional) remove empty lines");
    linesArr.push("var strings = []; ");
    linesArr.push("for (var i = 0; i < lines.length; i++) {");
    linesArr.push("  var s = lines[i];");
    linesArr.push("  // Simple trim (faster than regex in AE)");
    linesArr.push("  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);");
    linesArr.push("  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);");
    linesArr.push("  if (s.length) strings.push(s);");
    linesArr.push("}");
    linesArr.push("if (strings.length === 0) strings = ['(no lines in file)'];");
    linesArr.push("// Replace literal \\\\n with actual newlines for line breaks");
    linesArr.push("for (var j = 0; j < strings.length; j++) {");
    linesArr.push("  strings[j] = strings[j].replace(/\\\\n/g, String.fromCharCode(10));");
    linesArr.push("}");
    linesArr.push("var fpt = Math.max(1, Math.floor(thisComp.layer('Cycling Text Control').effect('Frames Per Text')('Slider')));");
    linesArr.push("var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;");
    linesArr.push("strings[idx];");
    var expr = linesArr.join(NL);

        // Apply the expression
        textLayer.property("Source Text").expression = expr;

        // Optional: name the layer for clarity if it was auto-created
        if (textLayer.name === "…") textLayer.name = "Cycling Text";

        // Basic sanity warning for *very* large inputs (AE expr length constraints vary)
        if (content.length > 200000) {
            alert("Heads up: that’s a very large list. If the expression feels sluggish, consider a keyframe-based approach instead.");
        }

    } catch (e) {
        alert("Error: " + e.message);
    } finally {
        app.endUndoGroup();
    }
})();

