/*  Cycle Two Text Layers From TSV (frames linked to slider)
    - Select a comp and TWO text layers, then run.
    - You'll be prompted to choose a .tsv file with tab-separated values.
    - Script creates/ensures a "Frames Per Text" slider and wires the expressions.
    - First selected layer uses first column, second selected layer uses second column.

    v9
*/

(function () {
    app.beginUndoGroup("Cycle Text From TXT");

    var comp = app.project.activeItem;
    if (!(comp instanceof CompItem)) {
        alert("Select a composition first.");
        app.endUndoGroup();
        return;
    }

    // Target text layers: need exactly two selected TextLayers, plus optional image layers
    var textLayer1 = null;
    var textLayer2 = null;
    var imageLayers = [];
    var textCount = 0;

    for (var sl = 0; sl < comp.selectedLayers.length; sl++) {
        var layer = comp.selectedLayers[sl];
        if (layer instanceof TextLayer) {
            textCount++;
            if (!textLayer1) textLayer1 = layer;
            else if (!textLayer2) textLayer2 = layer;
        } else if (layer instanceof AVLayer && !(layer instanceof TextLayer)) {
            imageLayers.push(layer);
        }
    }

    if (textCount !== 2) {
        alert("Please select exactly TWO text layers (optional: also select image layers for triggering).");
        app.endUndoGroup();
        return;
    }

    // Pick a .tsv file with tab-separated values
    var file = File.openDialog("Select a TSV file (tab-separated values)", "*.tsv;*.txt");
    if (!file) {
        app.endUndoGroup();
        return;
    }

    // Read file content safely
    try {
        // Prefer UTF-8; AE will still read ANSI if needed
        file.encoding = "UTF-8";
        if (!file.open("r")) throw new Error("Could not open file.");

        var content = file.read();
        file.close();

        // Normalize line endings to \n
        content = content.replace(/\r\n|\r|\n/g, "\n");        // normalize

        // Build a JS array literal of rows so the generated expression doesn't contain literal "\\n" escapes
        var rows = content.split("\n");
        var entryList = [];
        var parsedStrings = [];  // For preview
        for (var ri = 0; ri < rows.length; ri++) {
            var r = rows[ri];
            // Trim for preview
            var trimmed = r;
            while (trimmed.length && (trimmed.charCodeAt(0) <= 32)) trimmed = trimmed.substring(1);
            while (trimmed.length && (trimmed.charCodeAt(trimmed.length-1) <= 32)) trimmed = trimmed.substring(0, trimmed.length-1);
            if (trimmed.length) parsedStrings.push(trimmed);
            
            r = r.replace(/\\/g, "\\\\").replace(/\"/g, '\\\"').replace(/"/g, '\\"');
            entryList.push('"' + r + '"');
        }
        var entriesArrayLiteral = entryList.join(",");

        // Show preview dialog with first 5 rows split by tab
        var previewMsg = "Preview (first 5 entries):\n\n";
        for (var pi = 0; pi < Math.min(5, parsedStrings.length); pi++) {
            var parts = parsedStrings[pi].split("\t");
            previewMsg += (pi + 1) + ". [" + (parts[0] || "(empty)") + "] | [" + (parts[1] || "(empty)") + "]\n";
        }
        if (parsedStrings.length > 5) {
            previewMsg += "\n... and " + (parsedStrings.length - 5) + " more rows";
        }
        if (!confirm(previewMsg + "\n\nProceed with applying expressions?")) {
            app.endUndoGroup();
            return;
        }

        // Create a comp-level null object with the Frames Per Text slider
        var nullLayer = comp.layers.addNull();
        nullLayer.name = "Cycling Text Control";
        var fx = nullLayer.property("ADBE Effect Parade");
        var slider = fx.addProperty("ADBE Slider Control");
        slider.name = "Frames Per Text";
        slider.property("ADBE Slider Control-0001").setValue(10); // default

        // Build expression for first column (use join with a real newline to avoid literal "\\n" sequences)
        var NL = String.fromCharCode(10);
        var exprLines1 = [];
        exprLines1.push("// Auto-generated by script: reads first column from TSV");
        exprLines1.push("var lines = [" + entriesArrayLiteral + "]; ");
        exprLines1.push("var strings = []; ");
        exprLines1.push("for (var i = 0; i < lines.length; i++) {");
        exprLines1.push("  var parts = lines[i].split('\t');");
        exprLines1.push("  var s = parts[0] || ''; ");
        exprLines1.push("  // Simple trim");
        exprLines1.push("  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);");
        exprLines1.push("  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);");
        exprLines1.push("  if (s.length) strings.push(s);");
        exprLines1.push("}");
        exprLines1.push("if (strings.length === 0) strings = ['(no values in column 1)'];");
        exprLines1.push("// Replace literal \\\\n with actual newlines for line breaks");
        exprLines1.push("for (var j = 0; j < strings.length; j++) {");
        exprLines1.push("  strings[j] = strings[j].replace(/\\\\n/g, String.fromCharCode(10));");
        exprLines1.push("}");
        exprLines1.push("var fpt = Math.max(1, Math.floor(thisComp.layer('Cycling Text Control').effect('Frames Per Text')('Slider')));");
        exprLines1.push("var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;");
        exprLines1.push("strings[idx];");
        var expr1 = exprLines1.join(NL);

        // Build expression for second column
        var exprLines2 = [];
        exprLines2.push("// Auto-generated by script: reads second column from TSV");
        exprLines2.push("var lines = [" + entriesArrayLiteral + "]; ");
        exprLines2.push("var strings = []; ");
        exprLines2.push("for (var i = 0; i < lines.length; i++) {");
        exprLines2.push("  var parts = lines[i].split('\t');");
        exprLines2.push("  var s = parts[1] || ''; ");
        exprLines2.push("  // Simple trim");
        exprLines2.push("  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);");
        exprLines2.push("  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);");
        exprLines2.push("  if (s.length) strings.push(s);");
        exprLines2.push("}");
        exprLines2.push("if (strings.length === 0) strings = ['(no values in column 2)'];");
        exprLines2.push("// Replace literal \\\\n with actual newlines for line breaks");
        exprLines2.push("for (var j = 0; j < strings.length; j++) {");
        exprLines2.push("  strings[j] = strings[j].replace(/\\\\n/g, String.fromCharCode(10));");
        exprLines2.push("}");
        exprLines2.push("var fpt = Math.max(1, Math.floor(thisComp.layer('Cycling Text Control').effect('Frames Per Text')('Slider')));");
        exprLines2.push("var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;");
        exprLines2.push("strings[idx];");
        var expr2 = exprLines2.join(NL);

        // Apply the expressions
        textLayer1.property("Source Text").expression = expr1;
        textLayer2.property("Source Text").expression = expr2;

        // Image layer triggering: create Layer Controls on the null for each value found in the FIRST ROW
        // and wire image opacities so the selected image is visible while its trigger value is on screen.
        if (imageLayers.length > 0) {
            var firstRow = (rows.length > 0) ? rows[0] : "";
            var triggerParts = firstRow.split('\t');
            var triggers = [];
            for (var t = 0; t < triggerParts.length; t++) {
                var tv = triggerParts[t];
                while (tv.length && (tv.charCodeAt(0) <= 32)) tv = tv.substring(1);
                while (tv.length && (tv.charCodeAt(tv.length-1) <= 32)) tv = tv.substring(0, tv.length-1);
                if (tv.length) triggers.push(tv);
            }

            if (triggers.length === 0) {
                alert('No trigger values found in first row; skipping image wiring.');
            } else {
                var ctrlFx = nullLayer.property('ADBE Effect Parade');
                var layerControlNames = [];
                for (var i = 0; i < triggers.length; i++) {
                    var ctrlName = 'Image ' + (i+1);
                    var lc = ctrlFx.addProperty('ADBE Layer Control');
                    lc.name = ctrlName;
                    layerControlNames.push(ctrlName);
                    if (i < imageLayers.length) {
                        try { lc.property(1).setValue(imageLayers[i].index); } catch (e) { }
                    }
                }

                var escTriggers = [];
                var layerCtrlExprParts = [];
                for (var k = 0; k < triggers.length; k++) {
                    var raw = triggers[k].replace(/\\/g, '\\\\').replace(/'/g, "\\'");
                    escTriggers.push("'" + raw.toLowerCase() + "'");
                    layerCtrlExprParts.push("thisComp.layer('" + nullLayer.name.replace(/'/g, "\\'") + "').effect('" + layerControlNames[k].replace(/'/g, "\\'") + "')('Layer')");
                }

                var triggersArrayLiteral = '[' + escTriggers.join(',') + ']';
                var layerCtrlsArrayLiteral = '[' + layerCtrlExprParts.join(',') + ']';

                var imgExprLines = [];
                imgExprLines.push("// Auto-generated: show when cycling text matches a trigger and this layer is the linked layer");
                imgExprLines.push("var textVal = thisComp.layer('" + textLayer1.name.replace(/'/g, "\\'") + "').text.sourceText.toString().toLowerCase();");
                imgExprLines.push("var triggers = " + triggersArrayLiteral + ";");
                imgExprLines.push("var linked = " + layerCtrlsArrayLiteral + ";");
                imgExprLines.push("for (var ii = 0; ii < triggers.length; ii++) triggers[ii] = triggers[ii].replace(/\\\\n/g, String.fromCharCode(10));");
                imgExprLines.push("for (var i = 0; i < triggers.length; i++) { if (textVal === triggers[i] && linked[i] == thisLayer) return 100; }");
                imgExprLines.push("0;");
                var commonImgExpr = imgExprLines.join(NL);

                for (var il2 = 0; il2 < imageLayers.length; il2++) {
                    try { imageLayers[il2].opacity.expression = commonImgExpr; } catch (e) { $.writeln(e); }
                }

                alert('Created ' + triggers.length + ' image controls and wired ' + imageLayers.length + ' image layer(s).');
            }
        }

        // Optional: name the layers for clarity
        if (textLayer1.name === "…") textLayer1.name = "Cycling Text 1";
        if (textLayer2.name === "…") textLayer2.name = "Cycling Text 2";

        // Basic sanity warning for *very* large inputs (AE expr length constraints vary)
        if (content.length > 200000) {
            alert("Heads up: that’s a very large list. If the expressions feel sluggish, consider a keyframe-based approach instead.");
        }

    } catch (e) {
        alert("Error: " + e.message);
    } finally {
        app.endUndoGroup();
    }
})();

