/*  Cycle Three Text Layers From TSV (frames linked to slider)
    - Select a comp and THREE text layers, then run.
    - You'll be prompted to choose a .tsv file with tab-separated values.
    - Script creates/ensures a "Frames Per Text" slider and wires the expressions.
    - First selected layer uses first column, second uses second, third uses third.


    v9
*/

(function () {
    app.beginUndoGroup("Cycle Three Text Layers From TSV");

    var comp = app.project.activeItem;
    if (!(comp instanceof CompItem)) {
        alert("Select a composition first.");
        app.endUndoGroup();
        return;
    }

    // Target text layers: need exactly three selected TextLayers, plus optional image layers
    var textLayer1 = null;
    var textLayer2 = null;
    var textLayer3 = null;
    var imageLayers = [];
    var textCount = 0;

    for (var sl = 0; sl < comp.selectedLayers.length; sl++) {
        var layer = comp.selectedLayers[sl];
        } catch (e) {
            alert("Error: " + e.message);
        } finally {
            app.endUndoGroup();
        }
    })();
    // Build expression for first column (use join with a real newline to avoid literal "\\n" sequences)
    var NL = String.fromCharCode(10);
    var exprLines1 = [];
    exprLines1.push("// Auto-generated by script: reads first column from TSV");
    exprLines1.push("var lines = [" + entriesArrayLiteral + "]; ");
    exprLines1.push("var strings = []; ");
    exprLines1.push("for (var i = 0; i < lines.length; i++) {");
    exprLines1.push("  var parts = lines[i].split('\\t');");
    exprLines1.push("  var s = parts[0] || ''; ");
    exprLines1.push("  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);");
    exprLines1.push("  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);");
    exprLines1.push("  if (s.length) strings.push(s);");
    exprLines1.push("}");
    exprLines1.push("if (strings.length === 0) strings = ['(no values in column 1)'];");
    exprLines1.push("// Replace literal \\\\n with actual newlines for line breaks");
    exprLines1.push("for (var j = 0; j < strings.length; j++) {");
    exprLines1.push("  strings[j] = strings[j].replace(/\\\\n/g, String.fromCharCode(10));");
    exprLines1.push("}");
    exprLines1.push("var fpt = Math.max(1, Math.floor(thisComp.layer('Cycling Text Control').effect('Frames Per Text')('Slider')));");
    exprLines1.push("var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;");
    exprLines1.push("strings[idx];");
    var expr1 = exprLines1.join(NL);

    // Build expression for second column
    var exprLines2 = [];
    exprLines2.push("// Auto-generated by script: reads second column from TSV");
    exprLines2.push("var lines = [" + entriesArrayLiteral + "]; ");
    exprLines2.push("var strings = []; ");
    exprLines2.push("for (var i = 0; i < lines.length; i++) {");
    exprLines2.push("  var parts = lines[i].split('\\t');");
    exprLines2.push("  var s = parts[1] || ''; ");
    exprLines2.push("  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);");
    exprLines2.push("  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);");
    exprLines2.push("  if (s.length) strings.push(s);");
    exprLines2.push("}");
    exprLines2.push("if (strings.length === 0) strings = ['(no values in column 2)'];");
    exprLines2.push("// Replace literal \\\\n with actual newlines for line breaks");
    exprLines2.push("for (var j = 0; j < strings.length; j++) {");
    exprLines2.push("  strings[j] = strings[j].replace(/\\\\n/g, String.fromCharCode(10));");
    exprLines2.push("}");
    exprLines2.push("var fpt = Math.max(1, Math.floor(thisComp.layer('Cycling Text Control').effect('Frames Per Text')('Slider')));");
    exprLines2.push("var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;");
    exprLines2.push("strings[idx];");
    var expr2 = exprLines2.join(NL);

    // Build expression for third column
    var exprLines3 = [];
    exprLines3.push("// Auto-generated by script: reads third column from TSV");
    exprLines3.push("var lines = [" + entriesArrayLiteral + "]; ");
    exprLines3.push("var strings = []; ");
    exprLines3.push("for (var i = 0; i < lines.length; i++) {");
    exprLines3.push("  var parts = lines[i].split('\\t');");
    exprLines3.push("  var s = parts[2] || ''; ");
    exprLines3.push("  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);");
    exprLines3.push("  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);");
    exprLines3.push("  if (s.length) strings.push(s);");
    exprLines3.push("}");
    exprLines3.push("if (strings.length === 0) strings = ['(no values in column 3)'];");
    exprLines3.push("// Replace literal \\\\n with actual newlines for line breaks");
    exprLines3.push("for (var j = 0; j < strings.length; j++) {");
    exprLines3.push("  strings[j] = strings[j].replace(/\\\\n/g, String.fromCharCode(10));");
    exprLines3.push("}");
    exprLines3.push("var fpt = Math.max(1, Math.floor(thisComp.layer('Cycling Text Control').effect('Frames Per Text')('Slider')));");
    exprLines3.push("var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;");
    exprLines3.push("strings[idx];");
    var expr3 = exprLines3.join(NL);

        // Apply the expressions
        textLayer1.property("Source Text").expression = expr1;
        textLayer2.property("Source Text").expression = expr2;
        textLayer3.property("Source Text").expression = expr3;

        // Image layer triggering: create Layer Controls on the null for each value found in the FIRST ROW
        // and wire image opacities so the selected image is visible while its trigger value is on screen.
        if (imageLayers.length > 0) {
            // Read the first row of the TSV and split into trigger values
            var firstRow = (rows.length > 0) ? rows[0] : "";
            var triggerParts = firstRow.split('\t');
            var triggers = [];
            for (var t = 0; t < triggerParts.length; t++) {
                var tv = triggerParts[t];
                // Trim
                while (tv.length && (tv.charCodeAt(0) <= 32)) tv = tv.substring(1);
                while (tv.length && (tv.charCodeAt(tv.length-1) <= 32)) tv = tv.substring(0, tv.length-1);
                if (tv.length) triggers.push(tv);
            }

            if (triggers.length === 0) {
                alert('No trigger values found in first row; skipping image wiring.');
            } else {
                // Create one Layer Control per trigger on the null so the user can pick/change images later
                var ctrlFx = nullLayer.property('ADBE Effect Parade');
                var layerControlNames = [];
                for (var i = 0; i < triggers.length; i++) {
                    var ctrlName = 'Image ' + (i+1);
                    var lc = ctrlFx.addProperty('ADBE Layer Control');
                    lc.name = ctrlName;
                    layerControlNames.push(ctrlName);
                    // If the user selected image layers, set a sensible default in order
                    if (i < imageLayers.length) {
                        try { lc.property(1).setValue(imageLayers[i].index); } catch (e) { /* ignore */ }
                    }
                }

                // Build expression fragments: triggers array and layer-controls array
                var escTriggers = [];
                var layerCtrlExprParts = [];
                for (var k = 0; k < triggers.length; k++) {
                    // Escape backslashes and single quotes for embedding in single-quoted expression strings
                    var raw = triggers[k].replace(/\\/g, '\\\\').replace(/'/g, "\\'");
                    escTriggers.push("'" + raw.toLowerCase() + "'");
                    layerCtrlExprParts.push("thisComp.layer('" + nullLayer.name.replace(/'/g, "\\'") + "').effect('" + layerControlNames[k].replace(/'/g, "\\'") + "')('Layer')");
                }

                var triggersArrayLiteral = '[' + escTriggers.join(',') + ']';
                var layerCtrlsArrayLiteral = '[' + layerCtrlExprParts.join(',') + ']';

                // Expression applied to each selected image layer: show layer when its linked trigger is on screen
                var imgExprLines = [];
                imgExprLines.push("// Auto-generated: show when cycling text matches a trigger and this layer is the linked layer");
                imgExprLines.push("var textVal = thisComp.layer('" + textLayer1.name.replace(/'/g, "\\'") + "').text.sourceText.toString().toLowerCase();");
                imgExprLines.push("var triggers = " + triggersArrayLiteral + ";");
                imgExprLines.push("var linked = " + layerCtrlsArrayLiteral + ";");
                imgExprLines.push("// convert literal \\\\n+ sequences to actual newlines in triggers");
                imgExprLines.push("for (var ii = 0; ii < triggers.length; ii++) triggers[ii] = triggers[ii].replace(/\\\\n/g, String.fromCharCode(10));");
                imgExprLines.push("for (var i = 0; i < triggers.length; i++) { if (textVal === triggers[i] && linked[i] == thisLayer) return 100; }");
                imgExprLines.push("0;");
                var commonImgExpr = imgExprLines.join(NL);

                // Apply the expression to each image layer the user selected (so mapping works even if they change layer links later)
                for (var il2 = 0; il2 < imageLayers.length; il2++) {
                    try {
                        imageLayers[il2].opacity.expression = commonImgExpr;
                    } catch (e) {
                        $.writeln('Error applying opacity expr to ' + imageLayers[il2].name + ': ' + e);
                    }
                }

                alert('Created ' + triggers.length + ' image controls and wired ' + imageLayers.length + ' image layer(s).');
            }
        }

        // Optional: name the layers for clarity
        if (textLayer1.name === "…") textLayer1.name = "Cycling Text 1";
        if (textLayer2.name === "…") textLayer2.name = "Cycling Text 2";
        if (textLayer3.name === "…") textLayer3.name = "Cycling Text 3";

        if (content.length > 200000) {
            alert("Heads up: that's a very large list. If the expressions feel sluggish, consider a keyframe-based approach instead.");
        }

    } catch (e) {
        alert("Error: " + e.message);
    } finally {
            // Image layer triggering: create Layer Controls on the null for each value found in the FIRST ROW
            // and wire image opacities so the selected image is visible while its trigger value is on screen.
            if (imageLayers.length > 0) {
                // Read the first row of the TSV and split into trigger values
                var firstRow = (rows.length > 0) ? rows[0] : "";
                var triggerParts = firstRow.split('\t');
                var triggers = [];
                for (var t = 0; t < triggerParts.length; t++) {
                    var tv = triggerParts[t];
                    // Trim
                    while (tv.length && (tv.charCodeAt(0) <= 32)) tv = tv.substring(1);
                    while (tv.length && (tv.charCodeAt(tv.length-1) <= 32)) tv = tv.substring(0, tv.length-1);
                    if (tv.length) triggers.push(tv);
                }

                if (triggers.length === 0) {
                    alert('No trigger values found in first row; skipping image wiring.');
                } else {
                    // Create one Layer Control per trigger on the null so the user can pick/change images later
                    var ctrlFx = nullLayer.property('ADBE Effect Parade');
                    var layerControlNames = [];
                    for (var i = 0; i < triggers.length; i++) {
                        var ctrlName = 'Image ' + (i+1);
                        var lc = ctrlFx.addProperty('ADBE Layer Control');
                        lc.name = ctrlName;
                        layerControlNames.push(ctrlName);
                        // If the user selected image layers, set a sensible default in order
                        if (i < imageLayers.length) {
                            try { lc.property(1).setValue(imageLayers[i].index); } catch (e) { /* ignore */ }
                        }
                    }

                    // Build expression fragments: triggers array and layer-controls array
                    var escTriggers = [];
                    var layerCtrlExprParts = [];
                    for (var k = 0; k < triggers.length; k++) {
                        // Escape backslashes and single quotes for embedding in single-quoted expression strings
                        var raw = triggers[k].replace(/\\/g, '\\\\').replace(/'/g, "\\'");
                        escTriggers.push("'" + raw.toLowerCase() + "'");
                        layerCtrlExprParts.push("thisComp.layer('" + nullLayer.name.replace(/'/g, "\\'") + "').effect('" + layerControlNames[k].replace(/'/g, "\\'") + "')('Layer')");
                    }

                    var triggersArrayLiteral = '[' + escTriggers.join(',') + ']';
                    var layerCtrlsArrayLiteral = '[' + layerCtrlExprParts.join(',') + ']';

                    // Expression applied to each selected image layer: show layer when its linked trigger is on screen
                    var imgExprLines = [];
                    imgExprLines.push("// Auto-generated: show when cycling text matches a trigger and this layer is the linked layer");
                    imgExprLines.push("var textVal = thisComp.layer('" + textLayer1.name.replace(/'/g, "\\'") + "').text.sourceText.toString().toLowerCase();");
                    imgExprLines.push("var triggers = " + triggersArrayLiteral + ";");
                    imgExprLines.push("var linked = " + layerCtrlsArrayLiteral + ";");
                    imgExprLines.push("// convert literal \\\\n+ sequences to actual newlines in triggers");
                    imgExprLines.push("for (var ii = 0; ii < triggers.length; ii++) triggers[ii] = triggers[ii].replace(/\\\\n/g, String.fromCharCode(10));");
                    imgExprLines.push("for (var i = 0; i < triggers.length; i++) { if (textVal === triggers[i] && linked[i] == thisLayer) return 100; }");
                    imgExprLines.push("0;");
                    var commonImgExpr = imgExprLines.join(NL);

                    // Apply the expression to each image layer the user selected (so mapping works even if they change layer links later)
                    for (var il2 = 0; il2 < imageLayers.length; il2++) {
                        try {
                            imageLayers[il2].opacity.expression = commonImgExpr;
                        } catch (e) {
                            $.writeln('Error applying opacity expr to ' + imageLayers[il2].name + ': ' + e);
                        }
                    }

                    alert('Created ' + triggers.length + ' image controls and wired ' + imageLayers.length + ' image layer(s).');
                }
            }
