/*  Cycle Two Text Layers From TSV (frames linked to slider)
    - Select a comp and TWO text layers, then run.
    - You'll be prompted to choose a .tsv file with tab-separated values.
    - Script creates/ensures a "Frames Per Text" slider and wires the expressions.
    - First selected layer uses first column, second selected layer uses second column.
*/

(function () {
    app.beginUndoGroup("Cycle Text From TXT");

    var comp = app.project.activeItem;
    if (!(comp instanceof CompItem)) {
        alert("Select a composition first.");
        app.endUndoGroup();
        return;
    }

    // Target text layers: need exactly two selected TextLayers
    if (comp.selectedLayers.length !== 2 || 
        !(comp.selectedLayers[0] instanceof TextLayer) || 
        !(comp.selectedLayers[1] instanceof TextLayer)) {
        alert("Please select exactly TWO text layers.");
        app.endUndoGroup();
        return;
    }

    var textLayer1 = comp.selectedLayers[0];
    var textLayer2 = comp.selectedLayers[1];

    // Pick a .tsv file with tab-separated values
    var file = File.openDialog("Select a TSV file (tab-separated values)", "*.tsv;*.txt");
    if (!file) {
        app.endUndoGroup();
        return;
    }

    // Read file content safely
    try {
        // Prefer UTF-8; AE will still read ANSI if needed
        file.encoding = "UTF-8";
        if (!file.open("r")) throw new Error("Could not open file.");

        var content = file.read();
        file.close();

        // Normalize line endings to \n and escape for JS string literal
        // Then embed as a single big string and split in the expression
        content = content.replace(/\r\n|\r|\n/g, "\n");        // normalize
        var escaped = content
            .replace(/\\/g, "\\\\")                           // backslashes
            .replace(/"/g, '\\"')                             // double quotes
            .replace(/\n/g, "\\n");                           // newlines -> literal \n

        // Add/ensure the slider on the first text layer
        var fx = textLayer1.property("ADBE Effect Parade");
        var slider = fx.property("Frames Per Text") || fx.addProperty("ADBE Slider Control");
        slider.name = "Frames Per Text";
        slider.property("ADBE Slider Control-0001").setValue(10); // default

        // Build expression for first column
        var expr1 =
'// Auto-generated by script: reads first column from TSV\\n' +
'var raw = "' + escaped + '";\\n' +
'var lines = raw.split("\\n");\\n' +
'var strings = [];\\n' +
'for (var i = 0; i < lines.length; i++) {\\n' +
'  var parts = lines[i].split("\\t");\\n' +
'  var s = parts[0] || "";\\n' +
'  // Simple trim\\n' +
'  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);\\n' +
'  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);\\n' +
'  if (s.length) strings.push(s);\\n' +
'}\\n' +
'if (strings.length === 0) strings = ["(no values in column 1)"];\\n' +
'var fpt = Math.max(1, Math.floor(thisComp.layer("' + textLayer1.name + '").effect("Frames Per Text")("Slider")));\\n' +
'var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;\\n' +
'strings[idx];';

        // Build expression for second column
        var expr2 =
'// Auto-generated by script: reads second column from TSV\\n' +
'var raw = "' + escaped + '";\\n' +
'var lines = raw.split("\\n");\\n' +
'var strings = [];\\n' +
'for (var i = 0; i < lines.length; i++) {\\n' +
'  var parts = lines[i].split("\\t");\\n' +
'  var s = parts[1] || "";\\n' +
'  // Simple trim\\n' +
'  while (s.length && (s.charCodeAt(0) <= 32)) s = s.substring(1);\\n' +
'  while (s.length && (s.charCodeAt(s.length-1) <= 32)) s = s.substring(0, s.length-1);\\n' +
'  if (s.length) strings.push(s);\\n' +
'}\\n' +
'if (strings.length === 0) strings = ["(no values in column 2)"];\\n' +
'var fpt = Math.max(1, Math.floor(thisComp.layer("' + textLayer1.name + '").effect("Frames Per Text")("Slider")));\\n' +
'var idx = Math.floor(timeToFrames(time) / fpt) % strings.length;\\n' +
'strings[idx];';

        // Apply the expressions
        textLayer1.property("Source Text").expression = expr1;
        textLayer2.property("Source Text").expression = expr2;

        // Optional: name the layers for clarity
        if (textLayer1.name === "…") textLayer1.name = "Cycling Text 1";
        if (textLayer2.name === "…") textLayer2.name = "Cycling Text 2";

        // Basic sanity warning for *very* large inputs (AE expr length constraints vary)
        if (escaped.length > 200000) {
            alert("Heads up: that’s a very large list. If the expression feels sluggish, consider a keyframe-based approach instead.");
        }

    } catch (e) {
        alert("Error: " + e.message);
    } finally {
        app.endUndoGroup();
    }
})();

